# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/041_models.ResCNN.ipynb.

# %% auto 0
__all__ = ['ResCNN']

# %% ../../nbs/041_models.ResCNN.ipynb 3
from tsai.imports import *
from tsai.utils import *
from tsai.models.layers import *
from .patchTST import Projector

# %% ../../nbs/041_models.ResCNN.ipynb 5
class _ResCNNBlock(Module):
    def __init__(self, ni, nf, kss=[7, 5, 3], coord=False, separable=False, zero_norm=False):
        self.convblock1 = ConvBlock(ni, nf, kss[0], coord=coord, separable=separable)
        self.convblock2 = ConvBlock(nf, nf, kss[1], coord=coord, separable=separable)
        self.convblock3 = ConvBlock(nf, nf, kss[2], act=None, coord=coord, separable=separable, zero_norm=zero_norm)

        # expand channels for the sum if necessary
        self.shortcut = ConvBN(ni, nf, 1, coord=coord)
        self.add = Add()
        self.act = nn.ReLU()

    def forward(self, x):
        res = x
        x = self.convblock1(x)
        x = self.convblock2(x)
        x = self.convblock3(x)
        x = self.add(x, self.shortcut(res))
        x = self.act(x)
        return x


class ResCNN(Module):
    def __init__(self, c_out=320, num_classes=None, coord=False, separable=False, zero_norm=False, enc=True):
        nf = 64
        self.nf = nf
        self.enc = enc
        self.block1 = _ResCNNBlock(1, nf, kss=[7, 5, 3], coord=coord, separable=separable, zero_norm=zero_norm)
        self.block2 = ConvBlock(nf, nf * 2, 3, coord=coord, separable=separable, act=nn.LeakyReLU, act_kwargs={'negative_slope':.2})
        self.block3 = ConvBlock(nf * 2, nf * 4, 3, coord=coord, separable=separable, act=nn.PReLU)
        self.block4 = ConvBlock(nf * 4, nf * 2, 3, coord=coord, separable=separable, act=nn.ELU, act_kwargs={'alpha':.3})
        self.gap = nn.AdaptiveAvgPool1d(1)
        self.squeeze = Squeeze(-1)
        self.lin = nn.Linear(nf * 2, c_out)

        self.projector = Projector("4096-8192", c_out)

        if num_classes is not None:
            self.logits = nn.Sequential(
                # nn.Linear(self.embed_patch_aggr, num_classes),
                # get_activation_fn(act),
                nn.Linear(c_out, num_classes)
            )


    def forward(self, x, train_mode=""):
        # print(x.shape)
        # exit()
        if self.enc:
            bs, c, d = x.shape
            x = x.reshape(bs * c ,1, -1)
            x = self.block1(x)
            x = x.reshape(bs, self.nf, -1)
        else:
            x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.block4(x)
        x = self.squeeze(self.gap(x))
        x = self.lin(x)
        if train_mode == "train_vic":
            project = self.projector(x)
            return x, project
        z = x
        if hasattr(self, "logits"):
            if len(z.shape) ==2:
                z = z.unsqueeze(-1)
            z_pool = F.max_pool1d(z, kernel_size=z.size(2))
            z_pool = z_pool.squeeze(-1)
            # print(z_pool.shape)
            logits = self.logits(z_pool)
            return logits, z